In [1]:
# Import the requests library.
import requests
import numpy as np
import pandas as pd
# Import the requests library.
import requests
import datetime
from datetime import datetime
import matplotlib.pyplot as plt
# Dependencies for the wine API
import urllib
import json
# Import the API key.
from config import weather_api_key
import calendar

Token = 'tylRGHbxqiZUDNymMowCBFCuEqeULiWk'
Token_NOAA=Token
API_Token='Token d8f94b93417333267ca0edcca7dc14a9e035e1bb'

In [2]:
# https://github.com/crvaden/NOAA_API_v2
# https://towardsdatascience.com/getting-weather-data-in-3-easy-steps-8dc10cc5c859
# https://cran.r-project.org/web/packages/rnoaa/rnoaa.pdf
# file:///C:/Users/15124/Downloads/GHCND_documentation.pdf
# https://www1.ncdc.noaa.gov/pub/data/ghcn/daily/ghcnd-stations.txt

# For Loop with several zip codes since 1985 to 2015

In [36]:
bigdf = pd.DataFrame()
states = {
    'Napa': {
        'zip': '94558',
        'years': ['1985','1986','1987','1988','1989','1990', '1991','1993','1994','1995','1996','1997','1998','1999','2000','2001','2002','2003','2004','2005','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015']
        },
    'Walla': {
        'zip': '99362',
        'years': ['1985','1986','1987','1988','1989','1990', '1991','1993','1994','1995','1996','1997','1998','1999','2000','2001','2002','2003','2004','2005','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015']
        },
    'Columbia': {
        'zip': '98813',
        'years':['1985','1986','1987','1988','1989','1990', '1991','1993','1994','1995','1996','1997','1998','1999','2000','2001','2002','2003','2004','2005','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015']
        },
    'Sonoma': {
        'zip': '95476',
        'years': ['1985','1986','1987','1988','1989','1990', '1991','1993','1994','1995','1996','1997','1998','1999','2000','2001','2002','2003','2004','2005','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015']
        },
    'Santa': {
        'zip': '95062',
        'years': ['1985','1986','1987','1988','1989','1990', '1991','1993','1994','1995','1996','1997','1998','1999','2000','2001','2002','2003','2004','2005','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015']
        },
    'Yakima': {
        'zip': '98903',
        'years':['1985','1986','1987','1988','1989','1990', '1991','1993','1994','1995','1996','1997','1998','1999','2000','2001','2002','2003','2004','2005','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015']
        },
    'Dundee': {
        'zip': '97045',
        'years': ['1985','1986','1987','1988','1989','1990', '1991','1993','1994','1995','1996','1997','1998','1999','2000','2001','2002','2003','2004','2005','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015']
        },
    'Willamette': {
        'zip': '00077',
        'years': ['1985','1986','1987','1988','1989','1990', '1991','1993','1994','1995','1996','1997','1998','1999','2000','2001','2002','2003','2004','2005','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015']
        }
    #etc...
}

In [37]:
for state in states:
    small_df = pd.DataFrame()
    for year in states[state]['years']:
        zip = states[state]['zip']
        df_test = pd.DataFrame()
        #Print out 'working on year' to idenfity if script is running correctly
        print('working on year '+str(year))
        #make the api call for temp and precipitation
        #r = requests.get(f'https://www.ncdc.noaa.gov/cdo-web/api/v2/locations?locationcategoryid=ZIP:94558&datatypeid=TMIN&sortfield=name&sortorder=desc&units=standard&limit=1000&startdate='+year+'-01-01&enddate='+year+'-12-31', headers={'token':Token})
        r = requests.get(f'https://www.ncdc.noaa.gov/cdo-web/api/v2/data?datasetid=GHCND&locationid=ZIP:{zip}&datatypeid=TMAX&datatypeid=TMIN&units=standard&limit=1000&startdate='+year+'-01-01&enddate='+year+'-12-31', headers={'token':Token})
        #p = requests.get(f'https://www.ncdc.noaa.gov/cdo-web/api/v2/data?datasetid=GHCND&datatypeid=GHCND&limit=1000&stationid=GHCND:USC00046074&startdate='+year+'-01-01&enddate='+year+'-12-31', headers={'token':Token})
        #Load JSON data
        d = json.loads(r.text)
        #     print(d)
        #e = json.loads(p.text)
        items_MAX = [item for item in d['results'] if item['datatype']=='TMAX']
        items_MIN = [item for item in d['results'] if item['datatype']=='TMIN']
        # #get the date field from all average temperature readings
        dates_temp_MAX = [item['date'].split('T')[0] for item in items_MAX]
        dates_temp_MIN = [item['date'].split('T')[0] for item in items_MIN]
        df_test['date'] = dates_temp_MAX
        df_test['avgMaxTemp'+state] = np.nan
        for item in items_MAX:
            date = item['date'].split('T')[0]
            df_test.loc[df_test['date'] == date, ['avgMaxTemp'+state]] = item['value']
        df_test['avgMinTemp'+state] = np.nan
        for item in items_MIN:
            date = item['date'].split('T')[0]
            df_test.loc[df_test['date'] == date, ['avgMinTemp'+state]] = item['value']
        small_df = pd.concat([small_df,df_test])
    if bigdf.empty:
        bigdf = small_df
    else:
        bigdf = pd.merge(bigdf,small_df)

working on year 1985
working on year 1986
working on year 1987
working on year 1988
working on year 1989
working on year 1990
working on year 1991
working on year 1993
working on year 1994
working on year 1995
working on year 1996
working on year 1997
working on year 1998
working on year 1999
working on year 2000
working on year 2001
working on year 2002
working on year 2003
working on year 2004
working on year 2005
working on year 2006
working on year 2007
working on year 2008
working on year 2009
working on year 2010
working on year 2011
working on year 2012
working on year 2013
working on year 2014
working on year 2015
working on year 1985
working on year 1986
working on year 1987
working on year 1988
working on year 1989
working on year 1990
working on year 1991
working on year 1993
working on year 1994
working on year 1995
working on year 1996
working on year 1997
working on year 1998
working on year 1999
working on year 2000
working on year 2001
working on year 2002
working on year 2003
working on year 2004
working on year 2005
working on year 2006
working on year 2007
working on year 2008
working on year 2009
working on year 2010
working on year 2011
working on year 2012
working on year 2013
working on year 2014
working on year 2015
working on year 1985
working on year 1986
working on year 1987
working on year 1988
working on year 1989
working on year 1990
working on year 1991
working on year 1993
working on year 1994
working on year 1995
working on year 1996
working on year 1997
working on year 1998
working on year 1999
working on year 2000
working on year 2001
working on year 2002
working on year 2003
working on year 2004
working on year 2005
working on year 2006
working on year 2007
working on year 2008
working on year 2009
working on year 2010
working on year 2011
working on year 2012
working on year 2013
working on year 2014
working on year 2015
working on year 1985
working on year 1986
working on year 1987
working on year 1988
working on year 1989
working on year 1990
working on year 1991
working on year 1993
working on year 1994
working on year 1995
working on year 1996
working on year 1997
working on year 1998
working on year 1999
working on year 2000
working on year 2001
working on year 2002
working on year 2003
working on year 2004
working on year 2005
working on year 2006
working on year 2007
working on year 2008
working on year 2009
working on year 2010
working on year 2011
working on year 2012
working on year 2013
working on year 2014
working on year 2015
working on year 1985
working on year 1986
working on year 1987
working on year 1988
working on year 1989
working on year 1990
working on year 1991
working on year 1993
working on year 1994
working on year 1995
working on year 1996
working on year 1997
working on year 1998
working on year 1999
working on year 2000
working on year 2001
working on year 2002
working on year 2003
working on year 2004
working on year 2005
working on year 2006
working on year 2007
working on year 2008
working on year 2009
working on year 2010
working on year 2011
working on year 2012
working on year 2013
working on year 2014
working on year 2015
working on year 1985
working on year 1986
working on year 1987
working on year 1988
working on year 1989
working on year 1990
working on year 1991
working on year 1993
working on year 1994
working on year 1995
working on year 1996
working on year 1997
working on year 1998
working on year 1999
working on year 2000
working on year 2001
working on year 2002
working on year 2003
working on year 2004
working on year 2005
working on year 2006
working on year 2007
working on year 2008
working on year 2009
working on year 2010
working on year 2011
working on year 2012
working on year 2013
working on year 2014
working on year 2015
working on year 1985
working on year 1986
working on year 1987
working on year 1988
working on year 1989
working on year 1990
working on year 1991
working on year 1993
working on year 1994
working on year 1995
working on year 1996
working on year 1997
working on year 1998
working on year 1999
working on year 2000
working on year 2001
working on year 2002
working on year 2003
working on year 2004
working on year 2005
working on year 2006
working on year 2007
working on year 2008
working on year 2009
working on year 2010
working on year 2011
working on year 2012
working on year 2013
working on year 2014
working on year 2015
working on year 1985
working on year 1986
working on year 1987
working on year 1988
working on year 1989
working on year 1990
working on year 1991
working on year 1993
working on year 1994
working on year 1995
working on year 1996
working on year 1997
working on year 1998
working on year 1999
working on year 2000
working on year 2001
working on year 2002
working on year 2003
working on year 2004
working on year 2005
working on year 2006
working on year 2007
working on year 2008
working on year 2009
working on year 2010
working on year 2011
working on year 2012
working on year 2013
working on year 2014
working on year 2015

In [38]:
bigdf

,date,avgMaxTempNapa,avgMinTempNapa,avgMaxTempWalla,avgMinTempWalla,avgMaxTempColumbia,avgMinTempColumbia,avgMaxTempSonoma,avgMinTempSonoma,avgMaxTempSanta,avgMinTempSanta,avgMaxTempYakima,avgMinTempYakima,avgMaxTempDundee,avgMinTempDundee,avgMaxTempWillamette,avgMinTempWillamette
0,1985-01-01,59.0,29.0,20.0,17.0,17.0,-2.0,47.0,24.0,57.0,29.0,26.0,22.0,44.0,31.0,32.0,32.0
1,1985-01-01,59.0,29.0,20.0,17.0,17.0,-2.0,47.0,24.0,57.0,29.0,26.0,22.0,44.0,31.0,32.0,32.0
2,1985-01-02,54.0,31.0,22.0,17.0,14.0,-2.0,57.0,24.0,57.0,31.0,25.0,13.0,41.0,32.0,32.0,32.0
3,1985-01-02,54.0,31.0,22.0,17.0,14.0,-2.0,57.0,24.0,57.0,31.0,25.0,13.0,41.0,32.0,32.0,32.0
4,1985-01-02,54.0,31.0,22.0,17.0,14.0,-2.0,57.0,24.0,57.0,31.0,25.0,13.0,41.0,32.0,32.0,32.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36937,2015-09-06,88.0,42.0,68.0,50.0,69.0,43.0,90.0,48.0,90.0,47.0,73.0,40.0,66.0,48.0,52.0,38.0
36938,2015-09-06,88.0,42.0,68.0,50.0,69.0,43.0,90.0,48.0,90.0,47.0,73.0,40.0,66.0,48.0,52.0,38.0
36939,2015-09-06,88.0,42.0,68.0,50.0,69.0,43.0,90.0,48.0,90.0,47.0,73.0,40.0,66.0,48.0,52.0,38.0
36940,2015-09-07,92.0,47.0,73.0,50.0,76.0,47.0,92.0,50.0,95.0,50.0,79.0,46.0,73.0,59.0,64.0,40.0
36941,2015-09-07,92.0,47.0,73.0,50.0,76.0,47.0,92.0,50.0,95.0,50.0,79.0,46.0,73.0,59.0,64.0,40.0

In [41]:
#dataframe save as csv file
#bigdf.to_csv( 'weatherapi.csv', index = False)